micronaut:
  application:
    name: idiomcentric-service
  server:
    cors:
      enabled: true
    netty:
      access-logger:
        enabled: true # Enables the access logger
        logger-name: my-access-logger # A logger name, optional, default is `HTTP_ACCESS_LOGGER`
        log-format: common
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

  caches:
    headlines:
      charset: 'UTF-8'
      expire-after-write: 10m

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: username
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES


flyway:
  datasources:
    default:
      enabled: false

jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false

reddit:
  host: https://www.reddit.com
  limit: 10
  port: 443
  query: top.json
  rPath: r
  subReddit: worldnews
  t: day

jobs:
  reddit:
    fixedDelay: 10m
