micronaut:
  application:
    name: idiomcentric-service
  server:
    cors:
      enabled: true
    netty:
      access-logger:
        enabled: true # Enables the access logger
        logger-name: my-access-logger # A logger name, optional, default is `HTTP_ACCESS_LOGGER`
        log-format: common
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

  caches:
    headlines:
      charset: 'UTF-8'
      expire-after-write: 10m


  security:
    enabled: true
    token:
      jwt:
        enabled: true

  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  beans:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  refresh:
    enabled: true
    sensitive: false
  routes:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false
  stop:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  threaddump:
    enabled: true
    sensitive: false
  flyway:
    enabled: true
    sensitive: false


datasources:
  default:
    port: 5432
    hostname: localhost
    database: postgres
    url: jdbc:postgresql://${datasources.default.hostname}:${datasources.default.port}/${datasources.default.database}
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 2
    username: username
    password: password
    dialect: POSTGRES
    enableMigration: false


flyway:
  enabled: true
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration

jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false

reddit:
  host: https://www.reddit.com
  limit: 10
  port: 443
  query: top.json
  rPath: r
  subReddit: worldnews
  t: day

jobs:
  reddit:
    fixedDelay: 10m
