name: build-push
on:
  push:
    branches: [master]
    paths:
      - build/**
      - gradle/**
      - src/**
      - build.gradle.kts
      - gradle.properties
      - micronaut-cli.yml
      - openapi.properties
      - settings.gradle.kts

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-build
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build-push
        run: |
          ./gradlew ktlintCheck
          ./gradlew test
          ./gradlew dockerBuildNative
          docker tag idiomcentric-service:latest sevenleap/apps:idiomcentric-service
          docker push sevenleap/apps:idiomcentric-service
