name: build-push
on:
  push:
    branches:
      - master
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-build
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build-push
        run: |
          ./gradlew ktlintCheck
          ./gradlew test
          ./gradlew dockerBuildNative
          docker tag idiomcentric-service:latest sevenleap/apps:idiomcentric-service
          docker push sevenleap/apps:idiomcentric-service
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
